Repository ManageIQ/manageiq-providers-kubevirt, pull requests merged in 2018-10, with the labels that each got.

#118 [HAMMER] Update i18n catalog for hammer
  locale/ManageIQ_Providers_Kubevirt.pot
  locale/en/ManageIQ_Providers_Kubevirt.po
  locale/es/ManageIQ_Providers_Kubevirt.po
  locale/fr/ManageIQ_Providers_Kubevirt.po
  locale/ja/ManageIQ_Providers_Kubevirt.po
  locale/pt_BR/ManageIQ_Providers_Kubevirt.po
  locale/zh_CN/ManageIQ_Providers_Kubevirt.po
  zanata.xml
Labels: internationalization

#120 Travis - change postgres to 9.5
  .travis.yml
Labels: hammer/yes

#119 Removing inventory builder from Refresher
  app/models/manageiq/providers/kubevirt/infra_manager/inventory.rb
  app/models/manageiq/providers/kubevirt/infra_manager/refresher.rb
Labels: bug
