Repository ManageIQ/manageiq-providers-kubevirt, pull requests merged in 2018-12, with the labels that each got.

#126 refresh: Parser was never called
  app/models/manageiq/providers/kubevirt/infra_manager/refresh_worker/runner.rb
Labels: bug, hammer/yes

#127 Bump master travis.yml to ruby 2.3.8.
  .travis.yml
Labels: hammer/yes, test

#130 Bump master travis.yml to ruby 2.4.5
  .travis.yml
Labels: test
