Repository ManageIQ/manageiq-providers-kubevirt, pull requests merged in 2019-10, with the labels that each got.

#149 Add methods for for provider creation pluggable UI
  app/models/manageiq/providers/kubevirt/infra_manager.rb
Labels: enhancement

#152 Remove zanata.xml
  zanata.xml
Labels: cleanup

#151 Remove zanata from README
  README.md
Labels: cleanup

#153 Test ruby 2.5.7/2.6.5, see: ManageIQ/manageiq#19414
  .travis.yml
Labels: test
