Repository ManageIQ/manageiq-providers-kubevirt, pull requests merged in 2020-05, with the labels that each got.

#162 Fix README to point to travis-ci.com instead of travis-ci.org
  README.md
Labels: bug, developer

#163 Removing deprecated Gemnasium badge
  README.md
Labels: developer

#164 Add supports terminate feature
  app/models/manageiq/providers/kubevirt/infra_manager/vm/operations.rb
  spec/models/manageiq/providers/kubevirt/infra_manager/vm/operations_spec.rb
Labels: bug, jansa/yes?
