Repository ManageIQ/manageiq-providers-kubevirt, pull requests merged in 2021-03, with the labels that each got.

#183 Don't manually set the template's model_class
  app/models/manageiq/providers/kubevirt/inventory/persister.rb
Labels: refactoring

#184 Test with ruby 2.6.6 and 2.7.2 per ManageIQ/manageiq#19678
  .travis.yml
Labels: test

#181 Add systemd unit files for workers
  build/systemd_units/manageiq-providers-kubevirt_infra_manager_refresh.target
  build/systemd_units/manageiq-providers-kubevirt_infra_manager_refresh@.service
Labels: technical debt
