Repository ManageIQ/manageiq-providers-kubevirt, pull requests merged in 2022-02, with the labels that each got.

#197 Remove Hakiri
  README.md
Labels: cleanup, developer

#196 Fix KubeVirt Refresh
  app/models/manageiq/providers/kubevirt/infra_manager.rb
  app/models/manageiq/providers/kubevirt/infra_manager/refresher.rb
  app/models/manageiq/providers/kubevirt/inventory/parser.rb
  spec/factories/ext_management_system.rb
  spec/models/manageiq/providers/kubevirt/inventory/full_refresh_spec.rb
Labels: bug

#198 Bump kubevirt to 1.3.5 for openshift v4 fix
  manageiq-providers-kubevirt.gemspec
Labels: bug, morphy/yes?

#199 Switch to GitHub Actions
  .github/workflows/ci.yaml
  .travis.yml
  README.md
  bin/before_install
  bin/ci/after_script
  bin/setup
  manageiq-providers-kubevirt.gemspec
Labels: developer, test

#200 Add Build History Graph to README.md
  README.md
Labels: developer, test

#201 Cron for GitHub Actions
  .github/workflows/ci.yaml
Labels: developer, test
