Repository ManageIQ/manageiq-providers-kubevirt, pull requests merged in 2024-11, with the labels that each got.

#253 Testing with ruby 3.2, 3.3
  .github/workflows/ci.yaml
Labels: enhancement, test, ruby3.3

#256 KubeVirt Events Capture
  app/models/manageiq/providers/kubevirt/infra_manager/event_catcher.rb
  app/models/manageiq/providers/kubevirt/infra_manager/event_catcher/runner.rb
  app/models/manageiq/providers/kubevirt/infra_manager/event_parser.rb
  app/models/manageiq/providers/kubevirt/infra_manager/kubernetes_event_monitor.rb
  config/settings.yml
  systemd/manageiq-providers-kubevirt_infra_manager_event_catcher.target
  systemd/manageiq-providers-kubevirt_infra_manager_event_catcher@.service
Labels: enhancement

#257 Add VM event_groups to settings
  config/settings.yml
Labels: enhancement

#258 VM event parsing specs
  spec/models/manageiq/providers/kubevirt/infra_manager/event_parser_spec.rb
Labels: test
