Repository ManageIQ/manageiq-providers-kubevirt, pull requests merged in 2024-02, with the labels that each got.

#227 Drop require_nested and include_concern
  app/models/manageiq/providers/kubevirt/infra_manager.rb
  app/models/manageiq/providers/kubevirt/infra_manager/provision.rb
  app/models/manageiq/providers/kubevirt/infra_manager/refresh_worker.rb
  app/models/manageiq/providers/kubevirt/infra_manager/vm.rb
  app/models/manageiq/providers/kubevirt/infra_manager/vm/operations.rb
  app/models/manageiq/providers/kubevirt/inventory.rb
Labels: technical debt, rails7

#228 Test with ruby 3.1 and 3.0
  .github/workflows/ci.yaml
Labels: test

#229 drop unsupported_reason_add
  app/models/manageiq/providers/kubevirt/infra_manager/template.rb
  app/models/manageiq/providers/kubevirt/infra_manager/vm/operations.rb
Labels: refactoring

#230 [RADJABOV] Test radjabov with ruby 3.1
  .github/workflows/ci.yaml
Labels: test, ruby3.1
