Repository ManageIQ/manageiq-providers-kubevirt, pull requests merged in 2024-09, with the labels that each got.

#247 Openshift Virtualization subclassing changes
  app/models/manageiq/providers/kubevirt/infra_manager.rb
  app/models/manageiq/providers/kubevirt/infra_manager/refresh_worker/runner.rb
  app/models/manageiq/providers/kubevirt/inventory/parser.rb
  app/models/manageiq/providers/kubevirt/inventory/persister.rb
Labels: enhancement

#249 Fix Kubevirt client get resource by name calls
  app/models/manageiq/providers/kubevirt/infra_manager.rb
  app/models/manageiq/providers/kubevirt/infra_manager/provision/cloning.rb
  app/models/manageiq/providers/kubevirt/infra_manager/vm/operations.rb
  app/models/manageiq/providers/kubevirt/infra_manager/vm/operations/power.rb
  app/models/manageiq/providers/kubevirt/inventory/collector.rb
  app/models/manageiq/providers/kubevirt/inventory/parser.rb
  spec/fixtures/files/template-without-parameters.yml
  spec/models/manageiq/providers/kubevirt/inventory/parser_spec.rb
Labels: bug, radjabov/yes?

#250 Service Catalog Provisioning Support
  app/models/manageiq/providers/kubevirt/infra_manager/provision/cloning.rb
  app/models/manageiq/providers/kubevirt/infra_manager/provision_workflow.rb
  content/miq_dialogs/miq_provision_kubevirt_dialogs_template.yaml
Labels: bug, radjabov/yes?

#252 Move RefreshMemory under InfraManager
  app/models/manageiq/providers/kubevirt/infra_manager/refresh_memory.rb
  app/models/manageiq/providers/kubevirt/infra_manager/refresh_worker/runner.rb
Labels: refactoring, radjabov/yes?

#251 Allow override of collector/parser/persister classes
  app/models/manageiq/providers/kubevirt/infra_manager/refresh_worker/runner.rb
Labels: bug, radjabov/yes?
