Repository ManageIQ/manageiq-providers-kubevirt, pull requests merged in 2025-01, with the labels that each got.

#263 Restart a Virtual Machine
  app/models/manageiq/providers/kubevirt/infra_manager/vm.rb
  app/models/manageiq/providers/kubevirt/infra_manager/vm/operations.rb
  app/models/manageiq/providers/kubevirt/infra_manager/vm/operations/guest.rb
Labels: enhancement, radjabov/yes?

#272 Remove obsolete SPICE console option
  README.md
  app/models/manageiq/providers/kubevirt/infra_manager/connection.rb
  app/models/manageiq/providers/kubevirt/infra_manager/vm.rb
Labels: technical debt

#271 Delete unused offline_vm fixture files
  spec/fixtures/files/offline_vm.yml
  spec/fixtures/files/offline_vm_registry.yml
  spec/fixtures/files/offlinevm.json
  spec/fixtures/files/offlinevm_registry.json
Labels: technical debt

#273 Inherit renovate config from a central location
  renovate.json
Labels: developer
